MyShop.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyShop.Domain.Abstract;
using MyShop.Domain.Entities;
using MyShop.WebUI.Models;

namespace MyShop.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository _repository;

        public CartController(IProductRepository repository)
        {
            _repository = repository;
        }

        public ViewResult Index(ShoppingCart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public PartialViewResult Summary(ShoppingCart cart)
        {
            return PartialView(cart);
        }

        [HttpPost]
        public ActionResult Checkout(ShoppingCart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                //orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                if (Request.IsAjaxRequest())
                {
                    return PartialView("Completed");
                }
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
        public ViewResult Checkout()
        {

            return View(new ShippingDetails());
        }

        public RedirectToRouteResult AddToCart(ShoppingCart cart, int id, string returnUrl)
        {
            Product product = _repository.Products.FirstOrDefault(p => p.Id == id);
            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(ShoppingCart cart, int id, string returnUrl)
        {
            Product product = _repository.Products.FirstOrDefault(p => p.Id == id);
            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

    }
}

MyShop.WebUI/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyShop.Domain.Abstract;

namespace MyShop.WebUI.Controllers
{
    public class NavigationController : Controller
    {
        private IProductRepository _repository;

        public NavigationController(IProductRepository repository)
        {
            _repository = repository;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
              IEnumerable<string> categories = _repository.Products
                .Select(x => x.Category.Name)
                .Distinct()
                .OrderBy(x => x);
              return PartialView(categories);
        }

    }
}

MyShop.WebUI/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyShop.Domain.Abstract;
using MyShop.Domain.Entities;
using MyShop.WebUI.Models;

namespace MyShop.WebUI.Controllers
{
    public class ProductsController : Controller
    {
        private IProductRepository _repository;
        public int PageSize = 4;

        public ProductsController(IProductRepository repository)
        {
            _repository = repository;
        }


        public ActionResult List(string category, int page = 1)
        {
            ProductsListViewModel viewModel = new ProductsListViewModel();
            viewModel.CurrentCategory = category;
            viewModel.Products = _repository.Products
                .Where(p => category == null || p.Category.Name == category)
                .OrderBy(p => p.Id)
                .Skip((page - 1) * PageSize)
                .Take(PageSize);
            viewModel.PageNavigation = new PageNavigation
            {
                CurrentPage = page,
                ItemsPerPage = PageSize,
                TotalItems = category == null
                    ? _repository.Products.Count()
                    : _repository.Products.Where(e => e.Category.Name == category).Count()
            };
            if (Request.IsAjaxRequest())
            {
                return PartialView("_ProductsList", viewModel);
            }
            return View(viewModel);
        }
        public ActionResult ProductInfo(int id)
        {
            var product = _repository.Products.FirstOrDefault(x => x.Id == id);
            return View(product);
        }

        public string GetImage(int id)
        {
            Product prod = _repository.Products.FirstOrDefault(p => p.Id == id);
            return prod != null ? prod.ImagePath : null;
        }
    }
}

MyShop.WebUI/Views/Shared/ProductShort.cshtml
@model MyShop.Domain.Entities.Product

@if (Model.ImagePath != null)
{
    <div style="float: left; margin-right: 20px; width: 150px; text-align: center;">
        <img src="@Model.ImagePath" style="max-width: 140px; "/>
    </div>
 } 
<p class="style-title-list">
    <a href="/Products/@Model.Id">@Model.Name</a>
</p>
<!--<a class="add-cart-style-list" href="item.html">Купить</a>-->
@using (Html.BeginForm("AddToCart", "Cart"))
{
    @Html.HiddenFor(x => x.Id)
    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
    <input class="add-cart-style-list" type="submit" value="+ Добавить в корзину" />
}
<p class="style-price-list">@Model.Price.ToString()</p>
<div class="short-features">
    <p>@Model.Description</p>
</div>

MyShop.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Admin.css" rel="stylesheet" />
    @*Импорт файлов JavaScript для валидации на стороне клиента*@
    <script src="~/Scripts/jquery-1.7.1.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="Message">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

MyShop.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.8.2.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
</head>
<body>
    <div id="block-body">
        <div id="block-header">
            <div id="menu">
                <ul>
                    <li>@Html.ActionLink("Главная", "List", "Products")</li>
                    <li>@Html.ActionLink("Каталог", "List", "Products")</li>
                    <li>@Html.ActionLink("Оплата", "Payment", "Home")</li>
                    <li>@Html.ActionLink("Контакты", "Contact", "Home")</li>
                    <li>@{Html.RenderAction("Summary", "Cart");}</li>
                </ul>

            </div>
        </div>

        <div id="block-right">
            <div id="block-category">
                <p class="header-title">Категории товаров</p>
                @{ Html.RenderAction("Menu", "Navigation"); }
                <!--
                    <ul>
                        <li>
                            <a><img src="images/phone.png" id="phone-img" />Мобильные телефоны</a>
                            <ul class="category-section">
                                <li><a href="">Samsung</a></li>
                                <li><a href="">Lenovo</a></li>
                                <li><a href="">Sony</a></li>
                                <li><a href="">Huawei</a></li>
                                <li><a href=""><strong>Все модели</strong></a></li>

                            </ul>
                        </li>

                        <li>
                            <a><img src="images/notebook.png" id="notebook-img" />Ноутбуки</a>
                            <ul class="category-section">
                                <li><a
                                <li><a href="">Samsung</a></li>
                                <li><a href="">Lenovo</a></li>
                                <li><a href=""><strong>Все модели</strong></a></li>
                            </ul>
                        </li>

                        <li>
                            <a><img src="images/monoblock.png" id="monoblock-img" />Моноблоки</a>
                            <ul class="category-section">
                                <li><a href="">Samsung</a></li>
                                <li><a href="">Lenovo</a></li>
                                <li><a href=""><strong>Все модели</strong></a></li>
                            </ul>
                        </li>
                    </ul>
                    -->
            </div>
            
        </div>
        <div id="block-content">
            @RenderBody()
        </div>
        <div id="block-footer">
            
        </div>
    </div>
</body>
</html>